#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
    int t;
    scanf("%d\n", &t);

    for (int i = 0; i < t; i++)
    {
        unsigned char *cell = (unsigned char*)calloc(30000, 1);
        unsigned char *cells = cell;
        if (!cell)
        {
            fprintf(stderr, "Error allocating memory.\n");
            return 1;
        }
        ++cell;
        *cell = getchar();
        --cell;
        ++cell;
        ++cell;
        *cell = getchar();
        ++cell;
        *cell = getchar();
        --cell;
        while (*cell)
        {
            --*cell;
            ++cell;
            --*cell;
            ++cell;
            ++*cell;
            --cell;
            ++cell;
            --cell;
            --cell;
        }
        ++*cell;
        --*cell;
        ++cell;
        ++cell;
        while (*cell)
        {
            --*cell;
            --cell;
            --cell;
            ++*cell;
            ++cell;
            ++cell;
        }
        --cell;
        ++*cell;
        --*cell;
        ++cell;
        --cell;
        ++cell;
        --cell;
        --cell;
        --cell;
        while (*cell)
        {
            --*cell;
            ++*cell;
            --*cell;
            ++cell;
            --*cell;
            --cell;
            ++*cell;
            --*cell;
            --cell;
            ++*cell;
            ++cell;
        }
        --cell;
        while (*cell)
        {
            --*cell;
            ++cell;
            ++*cell;
            --cell;
        }
        ++cell;
        --cell;
        ++cell;
        ++cell;
        ++cell;
        ++cell;
        ++cell;
        ++cell;
        --cell;
        ++cell;
        ++*cell;
        ++*cell;
        --*cell;
        ++cell;
        ++cell;
        ++*cell;
        --*cell;
        ++cell;
        ++cell;
        ++cell;
        ++cell;
        ++cell;
        ++*cell;
        while (*cell)
        {
            ++cell;
            ++cell;
            --cell;
            ++cell;
            ++cell;
            ++cell;
            while (*cell)
            {
                --*cell;
            }
            --cell;
            while (*cell)
            {
                --*cell;
                --cell;
                ++cell;
                --*cell;
                ++*cell;
            }
            --cell;
            --cell;
            ++cell;
            while (*cell)
            {
                --*cell;
                ++*cell;
                --*cell;
            }
            --*cell;
            ++*cell;
            ++*cell;
            --*cell;
            ++*cell;
            --*cell;
            --cell;
            while (*cell)
            {
                --*cell;
            }
            --cell;
            ++cell;
            --cell;
            --cell;
            ++cell;
            while (*cell)
            {
                ++*cell;
                --*cell;
                --*cell;
                --*cell;
                ++*cell;
            }
            --cell;
            ++cell;
            --cell;
            --cell;
            --cell;
            --cell;
            ++*cell;
            --*cell;
            --cell;
            --cell;
            --cell;
            --cell;
            ++cell;
            --*cell;
            ++*cell;
            --cell;
            ++cell;
            --cell;
            --cell;
            --cell;
            ++cell;
            --cell;
            ++*cell;
            --*cell;
            --cell;
            --cell;
            while (*cell)
            {
                --*cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++*cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                --*cell;
                ++*cell;
                ++cell;
                ++*cell;
                --cell;
                --cell;
                --cell;
                ++cell;
                --cell;
                --cell;
                --cell;
                ++cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
            }
            ++cell;
            while (*cell)
            {
                --*cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                --cell;
                ++cell;
                --cell;
                ++cell;
                ++cell;
                --cell;
                ++cell;
                ++cell;
                ++*cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++*cell;
                --*cell;
                --cell;
                --cell;
                --cell;
                --cell;
            }
            ++cell;
            while (*cell)
            {
                --*cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                --cell;
                ++cell;
                ++*cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                --*cell;
                ++*cell;
                ++cell;
                --cell;
                ++cell;
                ++cell;
                ++*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++*cell;
                --*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --*cell;
                ++*cell;
                ++cell;
                --cell;
            }
            ++cell;
            ++cell;
            --*cell;
            ++*cell;
            ++*cell;
            --*cell;
            ++*cell;
            ++cell;
            ++*cell;
            --*cell;
            ++*cell;
            while (*cell)
            {
                --cell;
                --*cell;
            }
            --cell;
            while (*cell)
            {
                --*cell;
                ++cell;
                ++cell;
                --cell;
                ++cell;
                ++*cell;
                ++*cell;
                --*cell;
                --cell;
                --cell;
                --cell;
            }
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            while (*cell)
            {
                --*cell;
                --cell;
                --cell;
                --cell;
                ++*cell;
                --*cell;
                --*cell;
                ++*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++*cell;
                ++cell;
                ++cell;
                --cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
            }
            ++cell;
            while (*cell)
            {
                --*cell;
                --cell;
                --cell;
                --*cell;
                ++*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++*cell;
                --cell;
                ++cell;
                ++cell;
                ++*cell;
                --*cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
            }
            ++cell;
            while (*cell)
            {
                --*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++cell;
                --cell;
                --cell;
                --cell;
                ++cell;
                --cell;
                --cell;
                ++*cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
            }
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            --cell;
            ++cell;
            ++cell;
            ++*cell;
            while (*cell)
            {
                --*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++*cell;
                --*cell;
                --*cell;
                ++*cell;
                --cell;
                ++cell;
                --cell;
                ++*cell;
                --*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                while (*cell)
                {
                    --*cell;
                    ++cell;
                    ++cell;
                    ++*cell;
                    ++cell;
                    ++cell;
                    ++*cell;
                    --cell;
                    --cell;
                    --cell;
                    --cell;
                }
                ++*cell;
                --*cell;
                ++cell;
                while (*cell)
                {
                    --*cell;
                    ++cell;
                    ++cell;
                    ++*cell;
                    ++cell;
                    ++cell;
                    ++*cell;
                    --*cell;
                    ++*cell;
                    --cell;
                    --cell;
                    --cell;
                    --cell;
                }
                ++cell;
                while (*cell)
                {
                    --*cell;
                    --cell;
                    --cell;
                    ++*cell;
                    ++cell;
                    ++cell;
                }
                ++cell;
                while (*cell)
                {
                    --*cell;
                    --cell;
                    --cell;
                    ++*cell;
                    ++cell;
                    ++cell;
                }
                ++*cell;
                while (*cell)
                {
                    while (*cell)
                    {
                        --cell;
                        ++cell;
                        --*cell;
                    }
                    --*cell;
                    ++*cell;
                    ++*cell;
                    ++cell;
                    while (*cell)
                    {
                        --cell;
                        --*cell;
                    }
                    --cell;
                    ++*cell;
                    --*cell;
                    while (*cell)
                    {
                        ++*cell;
                        --*cell;
                        --*cell;
                        ++cell;
                        --cell;
                        ++cell;
                        ++cell;
                        --cell;
                        ++cell;
                        --*cell;
                        --cell;
                        --cell;
                        --cell;
                    }
                    ++cell;
                    ++cell;
                    --*cell;
                    ++*cell;
                    --*cell;
                    ++cell;
                    ++cell;
                    ++cell;
                    ++*cell;
                    ++cell;
                    while (*cell)
                    {
                        --cell;
                        --*cell;
                    }
                    --cell;
                    ++*cell;
                    --*cell;
                    while (*cell)
                    {
                        --*cell;
                        ++cell;
                        ++*cell;
                        ++cell;
                        while (*cell)
                        {
                            --*cell;
                            --cell;
                            --*cell;
                        }
                        --cell;
                        while (*cell)
                        {
                            ++cell;
                            ++cell;
                            while (*cell)
                            {
                                --*cell;
                                --cell;
                                --cell;
                                --*cell;
                                ++*cell;
                                --*cell;
                                ++cell;
                            }
                            --*cell;
                            --cell;
                            --cell;
                            while (*cell)
                            {
                                --*cell;
                                ++cell;
                                ++cell;
                                --cell;
                                --*cell;
                                ++cell;
                                ++*cell;
                                --*cell;
                                ++cell;
                                --*cell;
                                ++*cell;
                                --*cell;
                                --cell;
                                --cell;
                                --cell;
                                --cell;
                            }
                        }
                        --cell;
                    }
                    ++cell;
                    ++cell;
                    --*cell;
                    --cell;
                    --cell;
                    --cell;
                    --cell;
                    --cell;
                    ++*cell;
                    ++cell;
                    while (*cell)
                    {
                        ++cell;
                        --cell;
                        --cell;
                        --*cell;
                    }
                    --cell;
                    while (*cell)
                    {
                        ++cell;
                        ++*cell;
                        --*cell;
                        ++cell;
                        while (*cell)
                        {
                            --*cell;
                            ++*cell;
                            --cell;
                            --cell;
                            --*cell;
                            ++cell;
                        }
                        --cell;
                        --cell;
                        while (*cell)
                        {
                            --cell;
                        }
                    }
                    ++cell;
                    --*cell;
                    ++*cell;
                    --*cell;
                }
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                --cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                --cell;
                ++cell;
                ++*cell;
            }
            --*cell;
            --cell;
            --cell;
            --cell;
            ++cell;
            ++*cell;
            --*cell;
            --cell;
            --cell;
            --cell;
            ++cell;
            ++*cell;
            ++cell;
            --*cell;
            ++*cell;
            ++*cell;
            while (*cell)
            {
                --cell;
                --*cell;
            }
            --cell;
            while (*cell)
            {
                --*cell;
                ++*cell;
                ++cell;
                ++cell;
                ++*cell;
                while (*cell)
                {
                    --cell;
                    --cell;
                    --cell;
                    ++cell;
                    --*cell;
                    ++cell;
                    --*cell;
                    ++*cell;
                }
                --cell;
                --cell;
                while (*cell)
                {
                    ++cell;
                    ++cell;
                    ++cell;
                    ++*cell;
                    while (*cell)
                    {
                        --cell;
                        --*cell;
                        ++*cell;
                        --cell;
                        --cell;
                        --*cell;
                        ++cell;
                        ++cell;
                    }
                    --cell;
                    --cell;
                    --cell;
                    while (*cell)
                    {
                        --cell;
                    }
                }
            }
            ++cell;
            --*cell;
        }
        ++cell;
        ++cell;
        ++cell;
        ++cell;
        while (*cell)
        {
            --*cell;
        }
        --cell;
        --cell;
        --cell;
        --cell;
        --cell;
        --cell;
        --cell;
        --*cell;
        ++*cell;
        --cell;
        ++cell;
        --cell;
        --cell;
        --cell;
        --cell;
        --cell;
        --cell;
        --cell;
        while (*cell)
        {
            --*cell;
        }
        ++cell;
        ++cell;
        ++*cell;
        ++cell;
        ++*cell;
        while (*cell)
        {
            --cell;
            --*cell;
        }
        --cell;
        while (*cell)
        {
            --*cell;
            ++cell;
            ++cell;
            ++*cell;
            --cell;
            ++cell;
            --cell;
            --cell;
            --cell;
        }
        ++cell;
        ++*cell;
        ++cell;
        while (*cell)
        {
            --cell;
            --*cell;
        }
        --cell;
        while (*cell)
        {
            ++cell;
            ++cell;
            while (*cell)
            {
                --cell;
                --cell;
                --*cell;
                ++cell;
            }
            --cell;
            --cell;
            while (*cell)
            {
                --cell;
            }
        }
        ++cell;
        --*cell;
        while (*cell)
        {
            ++*cell;
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            --cell;
            ++*cell;
            ++*cell;
            --*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            --cell;
            --cell;
            --cell;
            --cell;
            --cell;
            --cell;
            ++*cell;
            ++cell;
            ++*cell;
            --*cell;
            while (*cell)
            {
                --cell;
                --cell;
                ++cell;
                --*cell;
            }
            --cell;
            while (*cell)
            {
                ++cell;
                ++cell;
                while (*cell)
                {
                    --cell;
                    --cell;
                    --*cell;
                    ++cell;
                }
                --cell;
                --cell;
                while (*cell)
                {
                    --cell;
                }
            }
            ++cell;
            --*cell;
            while (*cell)
            {
                ++*cell;
                ++*cell;
                ++cell;
                while (*cell)
                {
                    --cell;
                    --*cell;
                }
                --cell;
                while (*cell)
                {
                    --*cell;
                    ++cell;
                    ++cell;
                    --*cell;
                    --cell;
                    --cell;
                    --cell;
                }
                ++cell;
                ++cell;
                --*cell;
                ++cell;
                ++cell;
                ++*cell;
                ++cell;
                ++cell;
                ++*cell;
                ++cell;
                --*cell;
                while (*cell)
                {
                    --cell;
                    --*cell;
                }
                --cell;
                while (*cell)
                {
                    --cell;
                    --cell;
                    while (*cell)
                    {
                        --*cell;
                        ++cell;
                        ++cell;
                        ++cell;
                        ++*cell;
                        --cell;
                        --cell;
                        ++cell;
                        --cell;
                        --cell;
                    }
                    ++*cell;
                    --*cell;
                    ++cell;
                    ++cell;
                    ++cell;
                    ++cell;
                    ++cell;
                    ++*cell;
                    ++cell;
                    ++*cell;
                    while (*cell)
                    {
                        --cell;
                        ++cell;
                        --cell;
                        --*cell;
                    }
                    --cell;
                    ++cell;
                    --cell;
                    while (*cell)
                    {
                        --*cell;
                        ++cell;
                        ++cell;
                        ++*cell;
                        --cell;
                        --cell;
                        --cell;
                    }
                    --cell;
                    --cell;
                    --*cell;
                    --cell;
                }
                --cell;
                --cell;
                --cell;
                --cell;
                ++*cell;
                ++cell;
                while (*cell)
                {
                    --cell;
                    --*cell;
                }
                --cell;
                while (*cell)
                {
                    ++cell;
                    ++cell;
                    while (*cell)
                    {
                        --cell;
                        --cell;
                        --*cell;
                        ++cell;
                    }
                    --cell;
                    --cell;
                    while (*cell)
                    {
                        --cell;
                    }
                }
                ++cell;
                --*cell;
            }
            ++cell;
            ++cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            ++*cell;
            while (*cell)
            {
                --*cell;
                ++cell;
                ++*cell;
                ++*cell;
                ++*cell;
                ++*cell;
                ++*cell;
                ++*cell;
                --cell;
            }
            ++cell;
            while (*cell)
            {
                --*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++*cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
            }
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            ++cell;
            ++*cell;
            ++cell;
            --cell;
            ++cell;
            --*cell;
            ++*cell;
            while (*cell)
            {
                --cell;
                --*cell;
            }
            --cell;
            while (*cell)
            {
                ++cell;
                ++cell;
                while (*cell)
                {
                    --cell;
                    --cell;
                    --*cell;
                    ++cell;
                }
                --cell;
                --cell;
                while (*cell)
                {
                    --cell;
                }
            }
            ++cell;
            --*cell;
            while (*cell)
            {
                ++*cell;
                ++*cell;
                ++cell;
                while (*cell)
                {
                    --cell;
                    --*cell;
                }
                --cell;
                while (*cell)
                {
                    --*cell;
                    ++cell;
                    ++cell;
                    --*cell;
                    --cell;
                    --cell;
                    --cell;
                }
                ++cell;
                ++cell;
                --*cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                --cell;
                ++*cell;
                ++cell;
                ++*cell;
                while (*cell)
                {
                    --cell;
                    --*cell;
                }
                --cell;
                while (*cell)
                {
                    --*cell;
                    ++cell;
                    ++cell;
                    ++*cell;
                    --cell;
                    --cell;
                    --cell;
                }
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++cell;
                ++*cell;
                ++cell;
                while (*cell)
                {
                    --cell;
                    --*cell;
                }
                --cell;
                while (*cell)
                {
                    ++cell;
                    ++cell;
                    while (*cell)
                    {
                        --cell;
                        --cell;
                        --*cell;
                        ++cell;
                    }
                    --cell;
                    --cell;
                    while (*cell)
                    {
                        --cell;
                    }
                }
                ++cell;
                --*cell;
            }
            --cell;
            --cell;
            while (*cell)
            {
                --*cell;
            }
            --cell;
            --cell;
            --cell;
            --cell;
            --cell;
            ++*cell;
            ++cell;
            while (*cell)
            {
                --cell;
                --*cell;
            }
            --cell;
            while (*cell)
            {
                ++cell;
                ++cell;
                while (*cell)
                {
                    --cell;
                    --cell;
                    --*cell;
                    ++cell;
                }
                --cell;
                --cell;
                while (*cell)
                {
                    --cell;
                }
            }
            ++cell;
            --*cell;
        }
        --cell;
        --cell;
        while (*cell)
        {
            putchar(*cell);
            --cell;
        }

        free(cells);
        
        getchar();
        putchar('\n');
    }
    return 0;
}